version: '3.7'

services:
  minio1:                       # rename on different nodes
    hostname: minio1            # rename on different nodes
    image: quay.io/minio/minio:RELEASE.2021-11-09T03-21-45Z
    command: server --console-address ":9001" http://minio{1...3}/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "minio1:10.10.10.1"  # 1st node
      - "minio2:10.10.10.2"  # 2nd node
      - "minio3:10.10.10.3"  # 3rd node
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - data1-1:/data1          # rename on different nodes
      - data1-2:/data2          # rename on different nodes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:                      # rename on different nodes
  data1-2:                      # rename on different nodes
